name: SSH Login

on:
  schedule:
    - cron: '0 0 1,6,11,16,21,26,31 * *'  # 每个月的第1天、第6天、第11天等以此类推，每隔5天运行一次
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests
      
      - name: Run Python script
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          ANPUSH_TOKEN: ${{ secrets.ANPUSH_TOKEN }}
         
          
        run: python run.py
